<?php
$DEPARTMENT_CONFIG = array (
    'Art',
    'Administration',
    '6th Form',
    'Admission',
    'Parents Evening',
    'Preferences',
    'Principals Office',
    'Prom',
    'Reception',
    'Transition',
    'BusinessStudies',
    'Catering',
    'Computer Science',
    'Cover',
    'Creative',
    'Dance',
    'Design',
    'Drama',
    'DropDownDay',
    'Duke of Edinburgh',
    'English',
    'Exams',
    'Excellence',
    'Finance',
    'Geography',
    'Hazeley Plus',
    'Health and Social',
    'History',
    'HR',
    'Humanities',
    'ICT',
    'Inset Training',
    'Intervention',
    'IT Support',
    'Law',
    'Library',
    'Maths',
    'Media',
    'MFL',
    'MKHA',
    'Music',
    'Office',
    'Pastoral',
    'PE',
    'Personalisation',
    'Planners/Reports Cards',
    'Summer 2019 Ready',
    'PSHE/Citizenship',
    'Psychology',
    'R2L',
    'Reprographics',
    'Science',
    'Senior Leadership Team',
    'Site Team',
    '6th Form',
    'SLT',
    'Sociology',
    'Students',
    'textiles',
    'Trips',
    'wellbeing',
    'Work Experience',
    'Other'
  );


  $PRINT_TYPE_CONFIG = array (
    'Standard Print',
    'Colour',
    '2 to a page',
    'Size-A3',
    'Size-A4',
    'Size-A5',
    'Stapled-Top Left',
    'Stapled-Left Edge',
    'Hole Punched-Left x 4',
    'Hole Punched-Left x 2',
    'Booklet-A4',
    'Booklet-A5',
    'Laminated',
    'Other'
  );

  $PERIOD_CONFIG = array (
    'Period1' => 'Period1',
    'Period2' => 'Period2',
    'Break' => 'Break',
    'Period3' => 'Period3',
    'Period4' => 'Period4',
    'Period5' => 'Period5',
    'Period6' => 'Period6',
  );
